version: '3.8'

networks: 
    tig-net:
        driver: bridge

services:
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - 8086:8086
        environment:
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_DB: "iot"
            INFLUXDB_ADMIN_USER: "iotlnu"
            INFLUXDB_ADMIN_PASSWORD: "micropython"
        networks: 
            - tig-net
        volumes:
            - ./data/influxdb:/var/lib/influxdb

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports: 
            - 3000:3000
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin
        volumes:
            - ./data/grafana:/var/lib/grafana
        networks: 
            - tig-net
        restart: always        

    telegraf:
        image: telegraf:latest
        depends_on: 
            - "influxdb"
        environment:
            HOST_NAME: "telegraf"
            INFLUXDB_HOST: "influxdb"
            INFLUXDB_PORT: "8086"
            DATABASE: "iot"
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf
        tty: true
        networks: 
            - tig-net
        privileged: true
